name: bqplot-test
channels:
    - conda-forge
    - defaults
dependencies:
    - python
    - ipywidgets >=5.2.2
    - traitlets >=4.3.0
    - traittypes >=0.0.6
    - numpy >=1.10.4
    - pandas
    - pytest  # test dependency
    - pytest-cov  # test dependency
    - jupyterlab  # test dependency
    - selenium  # test dependency
    - mock  # test dependency
    - nose
